# Generated by Django 5.2.6 on 2025-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, choices=[('+20', '🇪🇬 Egypt (+20)'), ('+971', '🇦🇪 UAE (+971)'), ('+1', '🇺🇸 USA (+1)'), ('+44', '🇬🇧 UK (+44)'), ('+49', '🇩🇪 Germany (+49)')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('giza', 'Giza'), ('alexandria', 'Alexandria'), ('luxor', 'Luxor'), ('aswan', 'Aswan')], max_length=100, null=True),
        ),
    ]
