# Generated by Django 5.2.3 on 2025-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('available', 'Available for Adoption'), ('pending', 'Pending Adoption'), ('adopted', 'Adopted'), ('medical', 'Medical Hold')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
