# Generated by Django 5.2.6 on 2025-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_customuser_country_code_customuser_governorate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
